<form method="post" action="">

	<div data-role="main" class="ui-content">
		<div class="ui-grid-b">
			<div class="ui-block-a td-block-a">
				<input type="hidden" name="parent_id_old" value="<?php echo $this->castleLocation->parent_id_old; ?>">
			
				<div class="ui-field-contain td-field-contain">
					<label for="name">Name</label>
					<input type="text" name="Name" id="name" value="<?php echo (is_null($this->castleLocation->getId())) ? '' : $this->castleLocation->getName(); ?>">
				</div>
				
				<?php 
				if(count($this->parentLocations) > 0 && $this->castleLocation->getName() != 'jdx'): ?>
					<div class="ui-field-contain">
					    <label for="parent_id">Zugeh&ouml;rigkeit:</label>
					    <select name="ParentId" id="parent_id">
						    <?php 
							foreach($this->parentLocations as $parentLocation):
 								if($this->castleLocation->getId() != $parentLocation->getId()):?>
						        	<option value="<?php echo $parentLocation->getId(); ?>"><?php echo $parentLocation->getName(); ?></option>
									<?php 
 								endif;
							endforeach; ?>
					    </select>
					</div>
					<?php 
				endif; ?>
				
				<div class="td-right">
				    <input data-wrapper-class="td-right" data-theme="b" data-inline="true" name="save" value="Sichern" type="submit">
				    <input data-wrapper-class="td-right" data-theme="b" data-inline="true" name="cancel" value="Verwerfen" type="submit">
			    </div>
		    </div>
	    </div>
    </div>
</form>