<form method="post" action="">

	<div class="ui-field-contain">
	    <label for="type">Typ:</label>
	    <select name="Type" id="type">
	        <option value="Off">Off</option>
	        <option value="Def">Def</option>
	        <option value="Mix">Mix</option>
	    </select>
	</div>
	
	<div class="ui-field-contain">
		<label for="name">Name</label>
		<input type="text" name="Name" id="name" value="<?php echo $this->castleType->getName(); ?>">
	</div>
	
	<a href="/castletype/getlimit/<?php echo $this->castleType->getid(); ?>">Bev&ouml;lkerungslimit berechnen</a>
<!-- 	<button class="ui-btn ui-corner-all">Bev&ouml;lkerungslimit berechnen</button> -->
	
	<h3 class="ui-bar ui-bar-a">Gew&uuml;nschte Truppenst&auml;rke</h3>
	<div class="ui-field-contain">
         <label for="total-st">Speertr&auml;ger</label>
         <input name="TotalSt" id="total-st" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getTotalSt(); ?>" type="number">
    </div>
    <div class="ui-field-contain">
         <label for="total-sk">Schwertk&auml;mpfer</label>
         <input name="TotalSk" id="total-sk" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getTotalSk(); ?>" type="number">
    </div>
    <div class="ui-field-contain">
         <label for="total-bs">Bogensch&uuml;tzen</label>
         <input name="TotalBs" id="total-bs" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getTotalBs(); ?>" type="number">
    </div>
    <div class="ui-field-contain">
         <label for="total-as">Armbrustsch&uuml;tzen</label>
         <input name="TotalAs" id="total-as" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getTotalAs(); ?>" type="number">
    </div>
    <div class="ui-field-contain">
         <label for="total-pr">Panzerreiter</label>
         <input name="TotalPr" id="total-pr" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getTotalPr(); ?>" type="number">
    </div>
    <div class="ui-field-contain">
         <label for="total-lr">Lanzenreiter</label>
         <input name="TotalLr" id="total-lr" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getTotalLr(); ?>" type="number">
    </div>
    <div class="ui-field-contain">
         <label for="total-hk">Handkarren</label>
         <input name="TotalHk" id="total-hk" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getTotalHk(); ?>" type="number">
    </div>
    <div class="ui-field-contain">
         <label for="total-ok">Ochsenkarren</label>
         <input name="TotalOk" id="total-ok" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getTotalOk(); ?>" type="number">
    </div>
    
   	<h3 class="ui-bar ui-bar-a">F&uuml;r Missionen geplant</h3>
	<div class="ui-field-contain">
         <label for="mission-st">Speertr&auml;ger</label>
         <input name="MissionSt" id="mission-st" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getMissionSt(); ?>" type="number">
    </div>
    <div class="ui-field-contain">
         <label for="mission-sk">Schwertk&auml;mpfer</label>
         <input name="MissionSk" id="mission-sk" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getMissionSk(); ?>" type="number">
    </div>
    <div class="ui-field-contain">
         <label for="mission-bs">Bogensch&uuml;tzen</label>
         <input name="MissionBs" id="mission-bs" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getMissionBs(); ?>" type="number">
    </div>
    <div class="ui-field-contain">
         <label for="mission-as">Armbrustsch&uuml;tzen</label>
         <input name="MissionAs" id="mission-as" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getMissionAs(); ?>" type="number">
    </div>
    <div class="ui-field-contain">
         <label for="mission-pr">Panzerreiter</label>
         <input name="MissionPr" id="mission-pr" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getMissionPr(); ?>" type="number">
    </div>
    <div class="ui-field-contain">
         <label for="mission-lr">Lanzenreiter</label>
         <input name="MissionLr" id="mission-lr" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getMissionLr(); ?>" type="number">
    </div>

    <button class="ui-btn ui-btn-inline" name="save">Sichern</button>
    <button class="ui-btn ui-btn-inline" name="cancel">Abbruch</button>
</form>