<form method="post" action="">
	<div data-role="page" class="jqm-demos ui-responsive-panel" id="td-castletype-update-1" data-title="<?php echo APP_TITLE; ?>">
		<?php echo $this->render('header.phtml'); ?>
		
		<div data-role="main" class="ui-content">
			<div class="ui-grid-b">
				<div class="ui-block-a td-block-a">
			
					<fieldset data-role="controlgroup" data-type="horizontal">
				        <legend>Typ:</legend>
				        <input name="Type" id="type1a" value="Off" <?php echo ($this->castleType->getType() == 'Off') ? 'checked="checked"' : '';?> type="radio">
				        <label for="type1a">Off</label>
				        <input name="Type" id="type1b" value="Def" <?php echo ($this->castleType->getType() == 'Def') ? 'checked="checked"' : '';?> type="radio">
				        <label for="type1b">Def</label>
				        <input name="Type" id="type1c" value="Mix" <?php echo ($this->castleType->getType() == 'Mix') ? 'checked="checked"' : '';?> type="radio">
				        <label for="type1c">Mixed</label>
				    </fieldset>					
					
					<div class="ui-field-contain td-field-contain">
						<label for="name1">Name</label>
						<input type="text" name="Name" id="name1" value="<?php echo $this->castleType->getName(); ?>">
					</div>			
					
					<h3 class="ui-bar ui-bar-a td-link-margin-top">Bev&ouml;lkerung</h3>
					<div class="ui-field-contain td-field-contain-troops">
						<label for="maxpopulation1">Maximal</label>
						<input type="text" name="MaxPopulation" id="maxpopulation1" disabled="disabled" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getMaxPopulation(); ?>">
					</div>
					<div class="ui-field-contain td-field-contain-troops">
						<label class="td-label-width" for="freepopulation">Noch frei</label>
						<input type="text" name="FreePopulation" id="freepopulation" disabled="disabled" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getFreePopulation(); ?>">
					</div>
					<div class="ui-field-contain td-link-margin-top">
						<a href="#td-castletype-update-2">Bev&ouml;lkerungslimit berechnen</a>
					</div>
			    </div>
			
				<div class="ui-block-b td-block-b">
					<h3 class="ui-bar ui-bar-a">Gew&uuml;nschte Truppenst&auml;rke</h3>
					<div class="ui-field-contain td-field-contain-troops">
				         <label for="total-st">Speertr&auml;ger</label>
				         <input name="TotalSt" id="total-st" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getTotalSt(); ?>" type="number" onchange="calcFreePopulation();">
				    </div>
				    <div class="ui-field-contain td-field-contain-troops">
				         <label for="total-sk">Schwertk&auml;mpfer</label>
				         <input name="TotalSk" id="total-sk" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getTotalSk(); ?>" type="number" onchange="calcFreePopulation();">
				    </div>
				    <div class="ui-field-contain td-field-contain-troops">
				         <label for="total-bs">Bogensch&uuml;tzen</label>
				         <input name="TotalBs" id="total-bs" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getTotalBs(); ?>" type="number" onchange="calcFreePopulation();">
				    </div>
				    <div class="ui-field-contain td-field-contain-troops">
				         <label for="total-as">Armbrustsch&uuml;tzen</label>
				         <input name="TotalAs" id="total-as" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getTotalAs(); ?>" type="number" onchange="calcFreePopulation();">
				    </div>
				    <div class="ui-field-contain td-field-contain-troops">
				         <label for="total-pr">Panzerreiter</label>
				         <input name="TotalPr" id="total-pr" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getTotalPr(); ?>" type="number" onchange="calcFreePopulation();">
				    </div>
				    <div class="ui-field-contain td-field-contain-troops">
				         <label for="total-lr">Lanzenreiter</label>
				         <input name="TotalLr" id="total-lr" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getTotalLr(); ?>" type="number" onchange="calcFreePopulation();">
				    </div>
				    <div class="ui-field-contain td-field-contain-troops">
				         <label for="total-hk">Handkarren</label>
				         <input name="TotalHk" id="total-hk" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getTotalHk(); ?>" type="number" onchange="calcFreePopulation();">
				    </div>
				    <div class="ui-field-contain td-field-contain-troops">
				         <label for="total-ok">Ochsenkarren</label>
				         <input name="TotalOk" id="total-ok" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getTotalOk(); ?>" type="number" onchange="calcFreePopulation();">
				    </div>
				</div>
		    
		    	<div class="ui-block-c td-block-c">		    
				   	<h3 class="ui-bar ui-bar-a">F&uuml;r Missionen geplant</h3>
					<div class="ui-field-contain td-field-contain-troops">
				         <label for="mission-st">Speertr&auml;ger</label>
				         <input name="MissionSt" id="mission-st" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getMissionSt(); ?>" type="number" onchange="calcFreePopulation();">
				    </div>
				    <div class="ui-field-contain td-field-contain-troops">
				         <label for="mission-sk">Schwertk&auml;mpfer</label>
				         <input name="MissionSk" id="mission-sk" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getMissionSk(); ?>" type="number" onchange="calcFreePopulation();">
				    </div>
				    <div class="ui-field-contain td-field-contain-troops">
				         <label for="mission-bs">Bogensch&uuml;tzen</label>
				         <input name="MissionBs" id="mission-bs" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getMissionBs(); ?>" type="number" onchange="calcFreePopulation();">
				    </div>
				    <div class="ui-field-contain td-field-contain-troops">
				         <label for="mission-as">Armbrustsch&uuml;tzen</label>
				         <input name="MissionAs" id="mission-as" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getMissionAs(); ?>" type="number" onchange="calcFreePopulation();">
				    </div>
				    <div class="ui-field-contain td-field-contain-troops">
				         <label for="mission-pr">Panzerreiter</label>
				         <input name="MissionPr" id="mission-pr" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getMissionPr(); ?>" type="number" onchange="calcFreePopulation();">
				    </div>
				    <div class="ui-field-contain td-field-contain-troops">
				         <label for="mission-lr">Lanzenreiter</label>
				         <input name="MissionLr" id="mission-lr" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getMissionLr(); ?>" type="number" onchange="calcFreePopulation();">
				    </div>
				    <div class="td-right">
					    <input data-wrapper-class="td-right" data-theme="b" data-inline="true" name="save" value="Sichern" type="submit">
					    <input data-wrapper-class="td-right" data-theme="b" data-inline="true" name="cancel" value="Verwerfen" type="submit">
				    </div>
				</div>		    
				    
			</div>
		</div>
		<?php echo $this->render('footer.phtml'); ?>
	</div>
	
	<div data-role="page" class="jqm-demos ui-responsive-panel" id="td-castletype-update-2" data-title="<?php echo APP_TITLE; ?>">
		<?php echo $this->render('header.phtml'); ?>
		
		<div data-role="main" class="ui-content">
			<div class="ui-grid-b">
				<div class="ui-block-a td-block-a">

					<fieldset data-role="controlgroup" data-type="horizontal">
				        <legend>Typ:</legend>
				        <input name="Type2" id="type2a" value="Off" <?php echo ($this->castleType->getType() == 'Off') ? 'checked="checked"' : '';?> type="radio">
				        <label for="type2a">Off</label>
				        <input name="Type2" id="type2b" value="Def" <?php echo ($this->castleType->getType() == 'Def') ? 'checked="checked"' : '';?> type="radio">
				        <label for="type2b">Def</label>
				        <input name="Type2" id="type2c" value="Mix" <?php echo ($this->castleType->getType() == 'Mix') ? 'checked="checked"' : '';?> type="radio">
				        <label for="type2c">Mixed</label>
				    </fieldset>
					
							
					<div class="ui-field-contain td-field-contain">
						<label for="name2">Name</label>
						<input type="text" name="Name" id="name2" value="<?php echo $this->castleType->getName(); ?>">
					</div>
				
					<h3 class="ui-bar ui-bar-a td-link-margin-top">Bev&ouml;lkerung</h3>
					<div class="ui-field-contain td-field-contain-troops">
						<label for="maxpopulation2">Maximal</label>
						<input type="text" name="MaxPopulation" id="maxpopulation2" disabled="disabled" data-wrapper-class="number-4d" value="<?php echo $this->castleType->getMaxPopulation(); ?>">
					</div>
			 	</div>
			
				<div class="ui-block-b td-block-b">
					<h3 class="ui-bar ui-bar-a">Geb&auml;ude</h3>
					<div class="ui-field-contain td-field-contain-buildings">
				         <label for="bergfried">Bergfried</label>
				         <div data-role="controlgroup" class="td-controlgroup" data-type="horizontal">
					         <input data-icon="minus" data-iconpos="notext" value="-1" type="button" onclick="updatePopulation('bergfried', -1)">
					         <input name="Bergfried" id="bergfried" value="<?php echo $this->castleType->getBergfried(); ?>" data-wrapper-class="number-2d controlgroup-textinput ui-btn" type="number" onchange="updatePopulation('bergfried', 0)">
					         <input data-icon="plus" data-iconpos="notext" value="+1" type="button" onclick="updatePopulation('bergfried', 1)">
				         </div>
				    </div>
				    <div class="ui-field-contain td-field-contain-buildings">
				         <label for="zeughaus">Zeughaus</label>
				         <div data-role="controlgroup" class="td-controlgroup" data-type="horizontal">
					         <input data-icon="minus" data-iconpos="notext" value="-1" type="button" onclick="updatePopulation('zeughaus', -1)">
					         <input name="Zeughaus" id="zeughaus" value="<?php echo $this->castleType->getZeughaus(); ?>" data-wrapper-class="number-2d controlgroup-textinput ui-btn" type="number" onchange="updatePopulation('zeughaus', 0)">
					         <input data-icon="plus" data-iconpos="notext" value="+1" type="button" onclick="updatePopulation('zeughaus', 1)">
				         </div>
				    </div>
				    <div class="ui-field-contain td-field-contain-buildings">
				         <label for="taverne">Taverne</label>
				         <div data-role="controlgroup" class="td-controlgroup" data-type="horizontal">
					         <input data-icon="minus" data-iconpos="notext" value="-1" type="button" onclick="updatePopulation('taverne', -1)">
					         <input name="Taverne" id="taverne" value="<?php echo $this->castleType->getTaverne(); ?>" data-wrapper-class="number-2d controlgroup-textinput ui-btn" type="number" onchange="updatePopulation('taverne', 0)">
					         <input data-icon="plus" data-iconpos="notext" value="+1" type="button" onclick="updatePopulation('taverne', 1)">
				         </div>
				    </div>
				    <div class="ui-field-contain td-field-contain-buildings">
				         <label for="bibliothek">Bibliothek</label>
				         <div data-role="controlgroup" class="td-controlgroup" data-type="horizontal">
					         <input data-icon="minus" data-iconpos="notext" value="-1" type="button" onclick="updatePopulation('bibliothek', -1)">
					         <input name="Bibliothek" id="bibliothek" value="<?php echo $this->castleType->getBibliothek(); ?>" data-wrapper-class="number-2d controlgroup-textinput ui-btn" type="number" onchange="updatePopulation('bibliothek', 0)">
					         <input data-icon="plus" data-iconpos="notext" value="+1" type="button" onclick="updatePopulation('bibliothek', 1)">
				         </div>
				    </div>
				    <div class="ui-field-contain td-field-contain-buildings">
				         <label for="wehranlage">Wehranlage</label>
				         <div data-role="controlgroup" class="td-controlgroup" data-type="horizontal">
					         <input data-icon="minus" data-iconpos="notext" value="-1" type="button" onclick="updatePopulation('wehranlage', -1)">
					         <input name="Wehranlage" id="wehranlage" value="<?php echo $this->castleType->getWehranlage(); ?>" data-wrapper-class="number-2d controlgroup-textinput ui-btn" type="number" onchange="updatePopulation('wehranlage', 0)">
					         <input data-icon="plus" data-iconpos="notext" value="+1" type="button" onclick="updatePopulation('wehranlage', 1)">
				         </div>
				    </div>
				    <div class="ui-field-contain td-field-contain-buildings">
				         <label for="markt">Markt</label>
				         <div data-role="controlgroup" class="td-controlgroup" data-type="horizontal">
					         <input data-icon="minus" data-iconpos="notext" value="-1" type="button" onclick="updatePopulation('markt', -1)">
					         <input name="Markt" id="markt" value="<?php echo $this->castleType->getMarkt(); ?>" data-wrapper-class="number-2d controlgroup-textinput ui-btn" type="number" onchange="updatePopulation('markt', 0)">
					         <input data-icon="plus" data-iconpos="notext" value="+1" type="button" onclick="updatePopulation('markt', 1)">
				         </div>
				    </div>
				    <div class="ui-field-contain td-field-contain-buildings">
				         <label for="bauernhof">Bauernhof</label>
				         <div data-role="controlgroup" class="td-controlgroup" data-type="horizontal">
					         <input data-icon="minus" data-iconpos="notext" value="-1" type="button" onclick="updatePopulation('bauernhof', -1)">
					         <input name="Bauernhof" id="bauernhof" value="<?php echo $this->castleType->getBauernhof(); ?>" data-wrapper-class="number-2d controlgroup-textinput ui-btn" type="number" onchange="updatePopulation('bauernhof', 0)">
					         <input data-icon="plus" data-iconpos="notext" value="+1" type="button" onclick="updatePopulation('bauernhof', 1)">
				         </div>
				    </div>
				    <div class="ui-field-contain td-field-contain-buildings">
				         <label for="holzfaeller">Holzf&auml;ller</label>
				         <div data-role="controlgroup" class="td-controlgroup" data-type="horizontal">
					         <input data-icon="minus" data-iconpos="notext" value="-1" type="button" onclick="updatePopulation('holzfaeller', -1)">
					         <input name="Holzfaeller" id="holzfaeller" value="<?php echo $this->castleType->getHolzfaeller(); ?>" data-wrapper-class="number-2d controlgroup-textinput ui-btn" type="number" onchange="updatePopulation('holzfaeller', 0)">
					         <input data-icon="plus" data-iconpos="notext" value="+1" type="button" onclick="updatePopulation('holzfaeller', 1)">
				         </div>
				    </div>
				    <div class="ui-field-contain td-field-contain-buildings">
				         <label for="holzlager">Holzlager</label>
				         <div data-role="controlgroup" class="td-controlgroup" data-type="horizontal">
					         <input data-icon="minus" data-iconpos="notext" value="-1" type="button" onclick="updatePopulation('holzlager', -1)">
					         <input name="Holzlager" id="holzlager" value="<?php echo $this->castleType->getHolzlager(); ?>" data-wrapper-class="number-2d controlgroup-textinput ui-btn" type="number" onchange="updatePopulation('holzlager', 0)">
					         <input data-icon="plus" data-iconpos="notext" value="+1" type="button" onclick="updatePopulation('holzlager', 1)">
				         </div>
				    </div>
				    <div class="ui-field-contain td-field-contain-buildings">
				         <label for="steinbruch">Steinbruch</label>
				         <div data-role="controlgroup" class="td-controlgroup" data-type="horizontal">
					         <input data-icon="minus" data-iconpos="notext" value="-1" type="button" onclick="updatePopulation('steinbruch', -1)">
					         <input name="Steinbruch" id="steinbruch" value="<?php echo $this->castleType->getSteinbruch(); ?>" data-wrapper-class="number-2d controlgroup-textinput ui-btn" type="number" onchange="updatePopulation('steinbruch', 0)">
					         <input data-icon="plus" data-iconpos="notext" value="+1" type="button" onclick="updatePopulation('steinbruch', 1)">
				         </div>
				    </div>
				    <div class="ui-field-contain td-field-contain-buildings">
				         <label for="steinlager">Steinlager</label>
				         <div data-role="controlgroup" class="td-controlgroup" data-type="horizontal">
					         <input data-icon="minus" data-iconpos="notext" value="-1" type="button" onclick="updatePopulation('steinlager', -1)">
					         <input name="Steinlager" id="steinlager" value="<?php echo $this->castleType->getSteinlager(); ?>" data-wrapper-class="number-2d controlgroup-textinput ui-btn" type="number" onchange="updatePopulation('steinlager', 0)">
					         <input data-icon="plus" data-iconpos="notext" value="+1" type="button" onclick="updatePopulation('steinlager', 1)">
				         </div>
				    </div>
				    <div class="ui-field-contain td-field-contain-buildings">
				         <label for="erzmine">Erzmine</label>
				         <div data-role="controlgroup" class="td-controlgroup" data-type="horizontal">
					         <input data-icon="minus" data-iconpos="notext" value="-1" type="button" onclick="updatePopulation('erzmine', -1)">
					         <input name="Erzmine" id="erzmine" value="<?php echo $this->castleType->getErzmine(); ?>" data-wrapper-class="number-2d controlgroup-textinput ui-btn" type="number" onchange="updatePopulation('erzmine', 0)">
					         <input data-icon="plus" data-iconpos="notext" value="+1" type="button" onclick="updatePopulation('erzmine', 1)">
				         </div>
				    </div>  
				    <div class="ui-field-contain td-field-contain-buildings">
				         <label for="erzlager">Erzlager</label>
				         <div data-role="controlgroup" class="td-controlgroup" data-type="horizontal">
					         <input data-icon="minus" data-iconpos="notext" value="-1" type="button" onclick="updatePopulation('erzlager', -1)">
					         <input name="Erzlager" id="erzlager" value="<?php echo $this->castleType->getErzlager(); ?>" data-wrapper-class="number-2d controlgroup-textinput ui-btn" type="number" onchange="updatePopulation('erzlager', 0)">
					         <input data-icon="plus" data-iconpos="notext" value="+1" type="button" onclick="updatePopulation('erzlager', 1)">
				         </div>
				    </div>  
		        </div>
		    
		    	<div class="ui-block-c td-block-c">
					<h3 class="ui-bar ui-bar-a">Forschung Bibliothek</h3>
					<fieldset data-role="controlgroup">
				        <input name="Langbogen" id="langbogen" value="1" <?php if($this->castleType->getLangbogen()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('langbogen')">
				        <label id='langbogen-chk' for="langbogen">Langbogen</label>
				        <input name="Dreifelderwirtschaft" id="dreifelderwirtschaft" value="1" <?php if($this->castleType->getDreifelderwirtschaft()): echo "checked"; endif; ?> type="checkbox">
				        <label id='dreifelderwirtschaft-chk' for="dreifelderwirtschaft">Dreifelderwirtschaft</label>
				        <input name="Kummet" id="kummet" value="1" <?php if($this->castleType->getKummet()): echo "checked"; endif; ?> type="checkbox">
				        <label id='kummet-chk' for="kummet">Kummet</label>
				        <input name="Vorratskeller" id="vorratskeller" value="1" <?php if($this->castleType->getVorratskeller()): echo "checked"; endif; ?> type="checkbox">
				        <label id='vorratskeller-chk' for="vorratskeller">Vorratskeller</label>
				        <input name="Steigbuegel" id="steigbuegel" value="1" <?php if($this->castleType->getSteigbuegel()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('steigbuegel')">
				        <label id='steigbuegel-chk' for="steigbuegel">Steigb&uuml;gel</label>
				        <input name="Waffenschmied" id="waffenschmied" value="1" <?php if($this->castleType->getWaffenschmied()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('waffenschmied')">
				        <label id='waffenschmied-chk' for="waffenschmied">Waffenschmied</label>
				        <input name="Ruestungsschmied" id="ruestungsschmied" value="1" <?php if($this->castleType->getRuestungsschmied()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('ruestungsschmied')">
				        <label id='ruestungsschmied-chk' for="ruestungsschmied">R&uuml;stungsschmied</label>
				        <input name="Bierpruefer" id="bierpruefer" value="1" <?php if($this->castleType->getBierpruefer()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('bierpruefer')">
				        <label id='bierpruefer-chk' for="bierpruefer">Bierpr&uuml;fer</label>
				        <input name="Schwertschmied" id="schwertschmied" value="1" <?php if($this->castleType->getSchwertschmied()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('schwertschmied')">
				        <label id='schwertschmied-chk' for="schwertschmied">Schwertschmied</label>
				        <input name="Eisenhaertung" id="eisenhaertung" value="1" <?php if($this->castleType->getEisenhaertung()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('eisenhaertung')">
				        <label id='eisenhaertung-chk' for="eisenhaertung">Eisenh&auml;ertung</label>
				        <input name="Armbrust" id="armbrust" value="1" <?php if($this->castleType->getArmbrust()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('armbrust')">
				        <label id='armbrust-chk' for="armbrust">Armbrust</label>
				        <input name="Giftpfeile" id="giftpfeile" value="1" <?php if($this->castleType->getGiftpfeile()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('giftpfeile')">
				        <label id='giftpfeile-chk' for="giftpfeile">Giftpfeile</label>
				        <input name="Pferdezucht" id="pferdezucht" value="1" <?php if($this->castleType->getPferdezucht()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('pferdezucht')">
				        <label id='pferdezucht-chk' for="pferdezucht">Pferdezucht</label>
				        <input name="Waffenherstellung" id="waffenherstellung" value="1" <?php if($this->castleType->getWaffenherstellung()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('waffenherstellung')">
				        <label id='waffenherstellung-chk' for="waffenherstellung">Waffenherstellung</label>
				        <input name="Pferdepanzerung" id="pferdepanzerung" value="1" <?php if($this->castleType->getPferdepanzerung()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('pferdepanzerung')">
				        <label id='pferdepanzerung-chk' for="pferdepanzerung">Pferdepanzerung</label>
				        <input name="Schubkarren" id="schubkarren" value="1" <?php if($this->castleType->getSchubkarren()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('schubkarren')">
				        <label id='schubkarren-chk' for="schubkarren">Schubkarren</label>
				        <input name="Brandpfeile" id="brandpfeile" value="1" <?php if($this->castleType->getBrandpfeile()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('brandpfeile')">
				        <label id='brandpfeile-chk' for="brandpfeile">Brandpfeile</label>
				        <input name="Hufschmied" id="hufschmied" value="1" <?php if($this->castleType->getHufschmied()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('hufschmied')">
				        <label id='hufschmied-chk' for="hufschmied">Hufschmied</label>
				        <input name="Umgebungskarte" id="umgebungskarte" value="1" <?php if($this->castleType->getUmgebungskarte()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('umgebungskarte')">
				        <label id='umgebungskarte-chk' for="umgebungskarte">Umgebungskarte</label>
				        <input name="Zisterne" id="zisterne" value="1" <?php if($this->castleType->getZisterne()): echo "checked"; endif; ?> type="checkbox" onclick="calcPopulation('zisterne')">
				        <label id='zisterne-chk' for="zisterne">Zisterne</label>
				    </fieldset>
				    
				    <div class="td-right">
				    	<a href="#td-castletype-update-1" data-wrapper-class="td-right" data-theme="b" class="ui-btn ui-btn-b ui-btn-inline">Zur&uuml;ck</a>
				    </div>
				</div>
			</div>
		</div>
		<?php echo $this->render('footer.phtml'); ?>
	</div>
</form>