<div data-role="footer" class="ui-bar" data-position="fixed" data-theme='b'>				
	<h4>TotalDefense v0.1</h4>
<!-- <a href="<?php echo $this->layoutHelp; ?>" title="Hilfe" class="ui-btn ui-shadow ui-corner-all ui-icon-info ui-btn-icon-left ui-btn-icon-notext"></a>	  --> 
</div>
			
<div data-role="panel" data-display="push" data-theme="b" id="menue-panel">
   	<ul data-role="listview">
   		<li data-icon="delete"><a href="#" data-rel="close">Menue schlie&szlig;en</a></li>
   		<br/><br/>
		<li data-role="list-divider">Burgen</li>
	    <li><a href="/castle">Pflege</a></li>
	    <li><a href="/castle/list">&Uuml;bersicht</a></li>
	    <li><a href="/castletype">Typen</a></li>
	    <li><a href="/castle/import">Importieren</a></li>
	    <li data-role="list-divider">Standorte</li>
	    <li><a href="/castlelocation">Pflege</a>
	    <li><a href="/castlelocation/overview">&Uuml;bersicht</a></li>
	    <li><a href="/castlelocation/attach">Zuordnen</a></li>
	    <li><a href="/castlelocation/detach">Aufheben</a></li>
	    
	    <li data-role="list-divider">Verteidigung</li>
	    <li><a href="/defbridge">Def-Br&uuml;cke</a></li>
				    
	    <li data-role="list-divider">Angriffe</li>
	    <li><a href="#">Angriff</a></li>
	    <li><a href="#">Off-Br&uuml;cke</a></li>
	    <br/><br/>
	    <li><a href="/user">Profil</a></li>
	</ul>
</div>