<form method="post" action="">
	<div class="ui-grid-b">
		<div class="ui-block-a td-block-a">
			<div class="ui-field-contain td-field-contain">
				<label for="name">Name</label>
				<input type="text" name="Name" id="name" value="<?php echo $this->castle->getName(); ?>">
			</div>
			
			<div class="ui-field-contain td-field-contain">
			    <label for="select-native-1">Typ</label>
			    <select name="CastleTypeId" id="select-native-1">
			        <option value="1">Off</option>
			        <option value="2">Def</option>
			        <option value="3">Def 276a</option>
			        <option value="4">Def 278a</option>
			        <option value="5">Mix</option>
			    </select>
			</div>
			
			<div class="ui-field-contain td-field-contain">
			    <label for="select-native-1">Standort</label>
			    <select name="CastleLocationId" id="select-native-1">
			        <option value="0">Zentrum</option>
			        <option value="1">01</option>
			        <option value="2">01-10</option>
			        <option value="3">01-20</option>
			        <option value="4">02</option>
			        <option value="5">02-20</option>
			    </select>
			</div>

			<label for="coordinates">Koordinaten</label>
			<input type="text" name="Coordinates" id="coordinates" value="<?php echo $this->castle->getCoordinates(); ?>">

			<label class="td-label-margin-top" for="autodefcoordinates">Auto-Def Koordinaten</label>
			<input type="text" name="AutodefCoordinates" id="autodefcoordinates" value="<?php echo $this->castle->getAutodefCoordinates(); ?>">
			
			<h3 class="ui-bar ui-bar-a">Sonstige Angaben</h3>
		    <fieldset data-role="controlgroup">
		        <input name="UsageOff" id="usage_off" type="checkbox" value="<?php echo $this->castle->getUsageOff(); ?>">
		        <label for="usage_off">Off-Eins&auml;tze</label>
		        <input name="UsageDef" id="usage_def" type="checkbox" value="<?php echo $this->castle->getUsageDef(); ?>">
		        <label for="usage_def">Def-Eins&auml;tze</label>
		        <input name="MissionPriority" id="mission_priority" type="checkbox" value="<?php echo $this->castle->getMissionPriority(); ?>">
		        <label for="mission_priority">Prio auf Missionen</label>
		        <input name="EnvironmentCard" id="environment_card" type="checkbox" value="<?php echo $this->castle->getEnvironmentCard(); ?>">
		        <label for="environment_card">Umgebungskarte</label>
		    </fieldset>
	    </div>
	
		<div class="ui-block-b td-block-b">
			<h3 class="ui-bar ui-bar-a">Geplante Truppenst&auml;rke</h3>
			<div class="ui-field-contain td-field-contain-troops">
		         <label for="total-st">Speertr&auml;ger</label>
		         <input name="TotalSt" id="total-st" data-wrapper-class="number-4d" value="<?php echo $this->castle->getCurrentSt(); ?>" type="number">
		    </div>
		    <div class="ui-field-contain td-field-contain-troops">
		         <label for="total-sk">Schwertk&auml;mpfer</label>
		         <input name="TotalSk" id="total-sk" data-wrapper-class="number-4d" value="<?php echo $this->castle->getCurrentSk(); ?>" type="number">
		    </div>
		    <div class="ui-field-contain td-field-contain-troops">
		         <label for="total-bs">Bogensch&uuml;tzen</label>
		         <input name="TotalBs" id="total-bs" data-wrapper-class="number-4d" value="<?php echo $this->castle->getCurrentBs(); ?>" type="number">
		    </div>
		    <div class="ui-field-contain td-field-contain-troops">
		         <label for="total-as">Armbrustsch&uuml;tzen</label>
		         <input name="TotalAs" id="total-as" data-wrapper-class="number-4d" value="<?php echo $this->castle->getCurrentAs(); ?>" type="number">
		    </div>
		    <div class="ui-field-contain td-field-contain-troops">
		         <label for="total-pr">Panzerreiter</label>
		         <input name="TotalPrr" id="total-pr" data-wrapper-class="number-4d" value="<?php echo $this->castle->getCurrentPr(); ?>" type="number">
		    </div>
		    <div class="ui-field-contain td-field-contain-troops">
		         <label for="total-lr">Lanzenreiter</label>
		         <input name="TotalLr" id="total-lr" data-wrapper-class="number-4d" value="<?php echo $this->castle->getCurrentLr(); ?>" type="number">
		    </div>
		    <div class="ui-field-contain td-field-contain-troops">
		         <label for="total-hk">Handkarren</label>
		         <input name="TotalHk" id="total-hk" data-wrapper-class="number-4d" value="<?php echo $this->castle->getCurrentHk(); ?>" type="number">
		    </div>
		    <div class="ui-field-contain td-field-contain-troops">
		         <label for="total-ok">Ochsenkarren</label>
		         <input name="TotalOk" id="total-ok" data-wrapper-class="number-4d" value="<?php echo $this->castle->getCurrentOk(); ?>" type="number">
		    </div>
		    
		    <div class="ui-field-contain td-link-margin-top">			
				<a href="/castletype/create/p2">Bev&ouml;lkerungslimit berechnen</a>
			</div>
			
	    </div>
    
    	<div class="ui-block-c td-block-c">
		   	<h3 class="ui-bar ui-bar-a">F&uuml;r Missionen geplant</h3>
			<div class="ui-field-contain td-field-contain-troops">
		         <label for="mission-st">Speertr&auml;ger</label>
		         <input name="MissionSt" id="mission-st" data-wrapper-class="number-4d" value="<?php echo $this->castle->getMissionSt(); ?>" type="number">
		    </div>
		    <div class="ui-field-contain td-field-contain-troops">
		         <label for="mission-sk">Schwertk&auml;mpfer</label>
		         <input name="MissionSk" id="mission-sk" data-wrapper-class="number-4d" value="<?php echo $this->castle->getMissionSk(); ?>" type="number">
		    </div>
		    <div class="ui-field-contain td-field-contain-troops">
		         <label for="mission-bs">Bogensch&uuml;tzen</label>
		         <input name="MissionBs" id="mission-bs" data-wrapper-class="number-4d" value="<?php echo $this->castle->getMissionBs(); ?>" type="number">
		    </div>
		    <div class="ui-field-contain td-field-contain-troops">
		         <label for="mission-as">Armbrustsch&uuml;tzen</label>
		         <input name="MissionAs" id="mission-as" data-wrapper-class="number-4d" value="<?php echo $this->castle->getMissionAs(); ?>" type="number">
		    </div>
		    <div class="ui-field-contain td-field-contain-troops">
		         <label for="mission-pr">Panzerreiter</label>
		         <input name="MissionPr" id="mission-pr" data-wrapper-class="number-4d" value="<?php echo $this->castle->getMissionPr(); ?>" type="number">
		    </div>
		    <div class="ui-field-contain td-field-contain-troops">
		         <label for="mission-lr">Lanzenreiter</label>
		         <input name="MissionLr" id="mission-lr" data-wrapper-class="number-4d" value="<?php echo $this->castle->getMissionLr(); ?>" type="number">
		    </div>
		    
		    <div class="td-right">
			    <input data-wrapper-class="td-right" data-theme="b" data-inline="true" name="save" value="Sichern" type="submit">
			    <input data-wrapper-class="td-right" data-theme="b" data-inline="true" name="cancel" value="Verwerfen" type="submit">
		    </div>
		    
		</div>
	</div>
</form>