<form method="post" action="" class="attack-result">
	<h3 class="td-h3">
		<?php 
		echo ($this->target->getStartTime()) ? 'Startzeit: ' : 'Einschlag: ';
		echo $this->target->getDate() . ' / ' . $this->target->getTime() . ' Uhr'; ?>
	</h3>
	<div class="ui-grid-b">
		<div class="ui-block-a td-block-a">
			<fieldset data-role="controlgroup" data-type="horizontal">
				<legend class="td-legend-left">Typ:</legend>
		        <input name="FilterCastlesOff" id="fco" value="1" <?php echo ($this->target->getFilterCastlesOff() == true) ? 'checked="checked"' : '';?> type="checkbox">
		        <label for="fco">Off</label>
		        <input name="FilterCastlesDef" id="fcd" value="1" <?php echo ($this->target->getFilterCastlesDef() == true) ? 'checked="checked"' : '';?> type="checkbox">
		        <label for="fcd">Def</label>
		        <input name="FilterCastlesMix" id="fcm" value="1" <?php echo ($this->target->getFilterCastlesMix() == true) ? 'checked="checked"' : '';?> type="checkbox">
		        <label for="fcm">Mix</label>
		    </fieldset>
    	</div>
    	<div class="ui-block-b td-block-b">
		    <fieldset data-role="controlgroup" data-type="horizontal">
				<legend class="td-legend-left">Einheit:</legend>
		        <input name="FilterTroopsMarker" id="ftm" value="1" <?php echo ($this->target->getFilterTroopsMarker() == true) ? 'checked="checked"' : '';?> type="checkbox">
		        <label for="ftm">Takt</label>
		        <input name="FilterTroopsOff" id="fto" value="1" <?php echo ($this->target->getFilterTroopsOff() == true) ? 'checked="checked"' : '';?> type="checkbox">
		        <label for="fto">Off</label>
		        <input name="FilterTroopsDef" id="ftd" value="1" <?php echo ($this->target->getFilterTroopsDef() == true) ? 'checked="checked"' : '';?> type="checkbox">
		        <label for="ftd">Def</label>
		    </fieldset>
	    </div>
    	<div class="ui-block-b td-block-c">
		    <div class="ui-field-contain td-field-contain td-topmargin-9">
				<legend class="td-legend-left">Sortierung:</legend>
			    <select name="CastleTypeId" id="castletype">
		        	<option value="time">Laufzeit</option>
		        	<option value="silver">Silber</option>
		        	<option value="sk">Anzahl Sk</option>
		        	<option value="bs">Anzahl Bs</option>
		        	<option value="lr">Anzahl Lr</option>
			    </select>
			</div>			
		</div>
	</div>
	
	<div>
		<div class="ui-field-contain td-field-contain-troops">
        	<label for="total-silver">Silber</label>
			<input name="TotalSilver" id="total_silver" data-wrapper-class="number-6dx"  disabled="disabled" value="<?php echo $this->target->getTotalSilver(); ?>" type="number">
		</div>
		<div class="ui-field-contain td-field-contain-troops">
        	<label for="total-st">Speertr&auml;ger</label>
			<input name="TotalSt" id="total_st" data-wrapper-class="number-6dx"  disabled="disabled" value="<?php echo $this->target->getTotalSt(); ?>" type="number">
        </div>
        <div class="ui-field-contain td-field-contain-troops">
        	<label for="total-sk">Schwertk&auml;mpfer</label>
        	<input name="TotalSk" id="total_sk" data-wrapper-class="number-6dx"  disabled="disabled" value="<?php echo $this->target->getTotalSk(); ?>" type="number">
        </div>
        <input name="TotalBs" id="total_bs" data-wrapper-class="number-6dx"  disabled="disabled" value="<?php echo $this->target->getTotalBs(); ?>" type="number">
        <input name="TotalAs" id="total_as" data-wrapper-class="number-6dx"  disabled="disabled" value="<?php echo $this->target->getTotalAs(); ?>" type="number">
        <input name="TotalPr" id="total_pr" data-wrapper-class="number-6dx"  disabled="disabled" value="<?php echo $this->target->getTotalPr(); ?>" type="number">
        <input name="TotalLr" id="total_lr" data-wrapper-class="number-6dx"  disabled="disabled" value="<?php echo $this->target->getTotalLr(); ?>" type="number">
    </div>
	
	<table data-role="table" id="table-custom-2" class="tablesorter ui-body-d ui-shadow table-stripe ui-responsive" data-column-btn-theme="b" data-column-btn-text="Columns to display..." data-column-popup-theme="a">
         <thead>
           <tr class="ui-bar-d">
             <th>Nr.</th>
             <th>Burg</th>
             <th>Silber</th>
             <th class="takt">Ochsenkarren</th>
             <th class="takt">Handkarren</th>
             <th class="off">Schwert</th>
             <th class="def">Speer</th>
             <th class="def">Armbrust</th>
             <th class="off">Bogen</th>
             <th class="off">Lanzen</th>
             <th class="def">Panzer</th>
           </tr>
         </thead>
         <tbody>
         	<?php
         	$no = 0;
//         	echo "<xmp>"; var_dump($this->castles); exit;
         	foreach($this->castles as $castle): 
         		$no++;?>
            	<tr class="castle<?php $castleType = $castle->getCastleType(); //echo $castleType->getType(); ?>">
            		<td><?php echo $no; ?></td>
		            <td><a href="/castle/update/<?php echo $castle->getid(); ?>"><?php echo $castle->getName(); ?></a></td>
		            <td>
						<input type="text" name="silver<?php echo $castle->getId(); ?>" value="<?php echo $castle->getSilver(); ?>">
					</td>
		            <?php 
		            echo $this->ListEntry('ok', 'takt', $castle->getId(), $castle->date_ok, $castle->time_ok, $castle->color_ok, $castle->getCurrentOk(), 'Ochsenkarren');
		            echo $this->ListEntry('hk', 'takt', $castle->getId(), $castle->date_hk, $castle->time_hk, $castle->color_hk, $castle->getCurrentHk(), 'Handkarren');
		            echo $this->ListEntry('sk', 'off', $castle->getId(), $castle->date_sk, $castle->time_sk, $castle->color_sk, $castle->getCurrentSk(), 'Schwertk&auml;mpfer');
		            echo $this->ListEntry('st', 'def', $castle->getId(), $castle->date_st, $castle->time_st, $castle->color_st, $castle->getCurrentSt(), 'Speertr&auml;ger');
		            echo $this->ListEntry('as', 'def', $castle->getId(), $castle->date_as, $castle->time_as, $castle->color_as, $castle->getCurrentAs(), 'Armbrustsch&uuml;tzen');
		            echo $this->ListEntry('bs', 'off', $castle->getId(), $castle->date_bs, $castle->time_bs, $castle->color_bs, $castle->getCurrentBs(), 'Bogensch&uuml;tzen');
		            echo $this->ListEntry('lr', 'off', $castle->getId(), $castle->date_lr, $castle->time_lr, $castle->color_lr, $castle->getCurrentLr(), 'Lanzenreiter');
	            	echo $this->ListEntry('pr', 'def', $castle->getId(), $castle->date_pr, $castle->time_pr, $castle->color_pr, $castle->getCurrentPr(), 'Panzerreiter');?>
           		</tr>
           		<?php 
			endforeach; ?>
    	</tbody>
	</table>	
    <div class="td-right">
		<div class="ui-input-btn ui-btn ui-btn-b ui-btn-inline ui-corner-all ui-shadow">
	    	Bearbeiten
	    	<input name="update" type="submit">
	    </div> 
	</div>    
</form>