<!DOCTYPE html>
<html lang="de">

	<head>
	    <meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="apple-mobile-web-app-capable" content="yes">
		
		<link rel="shortcut icon" href="/img/totaldefense_32.png" />
		<link rel="apple-touch-icon" href="/img/totaldefense_64.png" />
		<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.css" />
		<link href="/css/totaldefense.css" rel="stylesheet" type="text/css"/>
		<script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
		<script src="/js/totaldefense.js"></script>
		<script src="http://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.js"></script>
	</head>
	
	<body>
		<?php echo $this->layout()->content; ?>
	</body>
</html>