<?php
// This file generated by Propel 1.7.1 convert-conf target
// from XML runtime conf file /Users/jd/DefaultWorkspace10/TotalDefense/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'TotalDefense' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=TotalDefense',
        'user' => 'root',
        'password' => 'jdmac',
        'settings' => 
        array (
          'charset' => 
          array (
            'value' => 'utf8',
          ),
        ),
        'options' => 
        array (
          'MYSQL_ATTR_INIT_COMMAND' => 
          array (
            'value' => 'SET NAMES utf8 COLLATE utf8_german2_ci',
          ),
        ),
      ),
    ),
    'default' => 'TotalDefense',
  ),
  'generator_version' => '1.7.1',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-orm-conf.php');
return $conf;